services:
  - type: web
    name: SmartCropRecommendationSystem
    env: python
    rootDir: Backend
    buildCommand: ./build.sh
    startCommand: gunicorn smartcrop.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9